ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "/data/zgr/code/OpenRLHF/"}' \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 1 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 1 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 1 \
   --vllm_num_engines 1 \
   --vllm_tensor_parallel_size 1 \
   --pretrain /data/zgr/code/OpenRLHF/ckpts/Qwen2-VL-2B-Instruct \
   --reward_pretrain /data/zgr/code/OpenRLHF/ckpts/Qwen2-VL-2B-Instruct \
   --save_path /data/zgr/code/OpenRLHF/ckpts/Qwen2-VL-2B-Instruct-rlhf \
   --micro_train_batch_size 1 \
   --train_batch_size 1 \
   --micro_rollout_batch_size 1 \
   --rollout_batch_size 1 \
   --n_samples_per_prompt 1 \
   --max_epochs 1 \
   --max_samples 100000 \
   --generate_max_len 10 \
   --advantage_estimator reinforce \
   --use_prm \
   --placeholder_token 151653 \
   --reward_tokens 10 12 \
   --zero_stage 0 \
   --lora_rank 64 \
   --target_modules q_proj \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --init_kl_coef 0.01 \
   --prompt_data /data/zgr/code/OpenRLHF/data/prompts.json \
   --input_key message \
   --normalize_reward \
   --gradient_checkpointing \
   --save_steps -1 \
   --ckpt_path /data/zgr/code/OpenRLHF/ckpts/Qwen2-VL-2B-Instruct-rlhf 